#!/bin/bash

echo "Install /boot/config-$1"
cp .config /boot/config-$1
echo "Install"
/sbin/installkernel $*
echo "Fix DT " /boot/loader/entries/*-$1.conf
for i in /boot/loader/entries/*-$1.conf; do
    perl -pi -e "s/^$/devicetree \/dtbs\/$1\/qcom\/x1e80100-lenovo-yoga-slim7x.dtb/" $i
done
