#!/bin/bash

if [ "$1" == "" ]
then
   echo "You must specify the version to remove"
   exit 1
fi

vmlinuz="/boot/vmlinuz-$1"
initramfs="/boot/initramfs-$1.img"
modules="/lib/modules/$1"
loader="/boot/loader/entries/*-$1.conf"

echo $loader

if [ ! -e "$vmlinuz" ]
then
   echo "Kernel not installed: no $vmlinuz"
   exit 2
fi

echo rm -rf "$vmlinuz" "$initramfs" "$modules" "$loader"
sudo rm -rf "$vmlinuz" "$initramfs" "$modules" $loader
echo "Updating bootlist"
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
